# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Benedict Egima
tagline:          'Coder, Blogger, Teacher'
description:      "10 years from now, you will regret more the things you didn't do than those you did"
url:              https://egimaben.github.io
baseurl:          /

author:
  name:           'Benedict Egima Ayiko'
  role:           Senior Software Developer @Andela, Senior Backend Engineer @Coursera
  url:            https://egimaben.github.io
  github:         egimaben
  twitter:        egimaben
  email:          benikod@gmail.com
  stackoverflow:  3067615/egimaben
  linkedin:       egimaben

paginate:         5
excerpt_separator: <!--more-->

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/egimaben/egimaben.github.io
repository:       egimaben/egimaben.github.io

#plugins
plugins:         [jekyll-paginate,jekyll-gist,jekyll-github-metadata]
paginate_path: "page:num"

animation: true
